language: julia
julia:
  - 1.4.1
branches:
  only:
  - master
  - stg
  - /dev-ci*/
addons:
  apt:
    - python3
    - python3-pip
before_install:
  - pip3 install --user --upgrade pip
  - pip3 install fbprophet